// Copyright (c) 2023 Smoking Carrots. All rights reserved.

#include "PXCustomLogs.h"

DEFINE_LOG_CATEGORY(LogCamera);
DEFINE_LOG_CATEGORY(LogPlayer);
DEFINE_LOG_CATEGORY(LogCharacter);
DEFINE_LOG_CATEGORY(LogComponent);
DEFINE_LOG_CATEGORY(LogItem);
DEFINE_LOG_CATEGORY(LogProjectile);
DEFINE_LOG_CATEGORY(LogSprite);
DEFINE_LOG_CATEGORY(LogSubsystem);
DEFINE_LOG_CATEGORY(LogGameInstance);
DEFINE_LOG_CATEGORY(LogHUD);
DEFINE_LOG_CATEGORY(LogWidget);
DEFINE_LOG_CATEGORY(LogMenuManager);
DEFINE_LOG_CATEGORY(LogOwner);
DEFINE_LOG_CATEGORY(LogMusicCue);
DEFINE_LOG_CATEGORY(LogSaveGame);
DEFINE_LOG_CATEGORY(LogSound);
